### ISSUE TITLE
 If my test dataset has no annotation file and only image

### ISSUE THREAD

**Issue by 67aaa** [johnning2333/M2Doc#10]
Hello, I would like to ask how to modify the configuration file under m2doc_config if my test dataset has no annotation file and only image?

**Comment by johnning2333** [comment]
1) m2doc depends on OCR annotations as textual input. If you don't have any OCR annotations as input, it may not be appropriate to use m2doc to inference on your dataset.
2) And you may find other inference instructions in https://mmdetection.readthedocs.io/en/latest/user_guides/index.html

**Comment by 67aaa** [comment]
> 1. m2doc depends on OCR annotations as textual input. If you don't have any OCR annotations as input, it may not be appropriate to use m2doc to inference on your dataset.
> 2. And you may find other inference instructions in https://mmdetection.readthedocs.io/en/latest/user_guides/index.html

Thank you for your answer. However, I would like to ask for further clarification. During the training and evaluation phases, I have OCR annotations, JSON, and Annos, along with the corresponding PNG images. After training the model and obtaining the weights, I would like to use these weights to perform layout analysis on new test data. Since this new test data does not have annotation files, do I still need annotation files for the layout analysis, or can I proceed without them?

**Comment by johnning2333** [comment]
If you have OCR annotations for your new dataset, Yes. If you don't have OCR annotations for your new dataset, it may perform worse than you expect since you trained the network with OCR features.

**Comment by 67aaa** [comment]
> If you have OCR annotations for your new dataset, Yes. If you don't have OCR annotations for your new dataset, it may perform worse than you expect since you trained the network with OCR features.

My new data has OCR annotations and PNG, but no category annotations. Can it be used for testing？
