### ISSUE TITLE
Why is the MAP value very low when using the DINO-R50 weights for testing?

### ISSUE THREAD

**Issue by sunshine-app** [johnning2333/M2Doc#4]
bash mmdetection/tools/dist_test.sh mmdetection/m2doc_config/dino-4scale_w_m2doc_r50_doclaynet_12epoch.py dino_w_m2doc_r50_epoch_12.pth  1
![20240614](https://github.com/johnning2333/M2Doc/assets/17681768/a5ea18bf-74c3-4eb6-80e4-217e417bd3a2)

**Comment by johnning2333** [comment]
> bash mmdetection/tools/dist_test.sh mmdetection/m2doc_config/dino-4scale_w_m2doc_r50_doclaynet_12epoch.py dino_w_m2doc_r50_epoch_12.pth 1 ![20240614](https://private-user-images.githubusercontent.com/17681768/339647144-a5ea18bf-74c3-4eb6-80e4-217e417bd3a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDI3NjcsIm5iZiI6MTcxODQ0MjQ2NywicGF0aCI6Ii8xNzY4MTc2OC8zMzk2NDcxNDQtYTVlYTE4YmYtNzRjMy00ZWI2LTgwZTQtMjE3ZTQxN2JkM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA5MDc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MWNkNzM3NTNhZjliYTIwZDNiNjYwNGE4ZDBjZDU1MTQwOTIxMjg3MTg3MGY1OGJlYWMzYThiOWRlMGYwYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AH21R5pt7b4qOFyQtk77VuGNTc4lU6dv6H8H5JQI3f4)

Please be sure to use ocr annotations of doclaynet. And convert dataset ocr annotations into specific format using /data/doclaynet/ocr_anno_convert.py.

**Comment by JulioZhao97** [comment]
> bash mmdetection/tools/dist_test.sh mmdetection/m2doc_config/dino-4scale_w_m2doc_r50_doclaynet_12epoch.py dino_w_m2doc_r50_epoch_12.pth 1 ![20240614](https://private-user-images.githubusercontent.com/17681768/339647144-a5ea18bf-74c3-4eb6-80e4-217e417bd3a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzg4NzUsIm5iZiI6MTcyMzUzODU3NSwicGF0aCI6Ii8xNzY4MTc2OC8zMzk2NDcxNDQtYTVlYTE4YmYtNzRjMy00ZWI2LTgwZTQtMjE3ZTQxN2JkM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MDJhZDA2MWEwOGMzY2RiODZjNzBkZTk1OTFkZTE1NTA1NWQ0ZTNmMzVmYjllOWJkZDZhYTE3YTlhNTUyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mJve3ilpi_z2-y5dFMKEaNWDIAKqZso5dp_bwPutylU)

Hello!, can I ask you what version of ```pytorch, cuda, mmcv, mmengine, transformers``` did you use? I cannot run inference on my environment.

**Comment by johnning2333** [comment]
> > 
> Hello!, can I ask you what version of `pytorch, cuda, mmcv, mmengine, transformers` did you use? I cannot run inference on my environment.
you could create environment as:
conda create -n m2doc python=3.8 -y
conda activate m2doc
conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=10.2 -c pytorch
git clone https://github.com/johnning2333/M2Doc.git
cd M2Doc/mmdetection
pip install -v -e .
pip install transformers
pip install mmengine
mim install mmcv

**Comment by johnning2333** [comment]
> > bash mmdetection/tools/dist_test.sh mmdetection/m2doc_config/dino-4scale_w_m2doc_r50_doclaynet_12epoch.py dino_w_m2doc_r50_epoch_12.pth 1 ![20240614](https://private-user-images.githubusercontent.com/17681768/339647144-a5ea18bf-74c3-4eb6-80e4-217e417bd3a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzg4NzUsIm5iZiI6MTcyMzUzODU3NSwicGF0aCI6Ii8xNzY4MTc2OC8zMzk2NDcxNDQtYTVlYTE4YmYtNzRjMy00ZWI2LTgwZTQtMjE3ZTQxN2JkM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MDJhZDA2MWEwOGMzY2RiODZjNzBkZTk1OTFkZTE1NTA1NWQ0ZTNmMzVmYjllOWJkZDZhYTE3YTlhNTUyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mJve3ilpi_z2-y5dFMKEaNWDIAKqZso5dp_bwPutylU)
> 
> Hello!, can I ask you what version of `pytorch, cuda, mmcv, mmengine, transformers` did you use? I cannot run inference on my environment.

you could create environment as:
```
conda create -n m2doc python=3.8 -y
conda activate m2doc
conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=10.2 -c pytorch
git clone https://github.com/johnning2333/M2Doc.git
cd M2Doc/mmdetection
pip install -v -e .
pip install transformers
pip install mmengine
mim install mmcv
```
