### ISSUE TITLE
How to get ocr_anno files?

### ISSUE THREAD

**Issue by RicoJYang** [johnning2333/M2Doc#5]
In the ocr_anno_convert.py file, is ocr_anno_path the result of the OCR program output? , save_anno_path is an empty newly created folder. Can the author provide the OCR software used? Thank you very much.

**Comment by johnning2333** [comment]
> In the ocr_anno_convert.py file, is ocr_anno_path the result of the OCR program output? , save_anno_path is an empty newly created folder. Can the author provide the OCR software used? Thank you very much.

That's just a converting script to convert DocLayNet OCR Annotations(Provided by the Dataset) into our training format.
Please make sure you download the DocLayNet dataset first.
